#!/Users/chuckbergeron/.rvm/rubies/ruby-1.8.7-p330/bin/ruby
str = "TAGCAATAACCCCCCCGTCTTTTTTATAGTGCGTAGACCGCAGTGCTTTCGACGCCGATGATTTCACCAACGAAACCTCGTGCTTTAATATTAATTTTGGGGCCGAGAAGTCCCTAAATCTGCCAAGCGGACGTCTAAATTGGAAGCTGCCGCAGTTCACGCATTCTACGCTCGAATCATAGTGCACCAACCGAGCGTACTGCGGGGCGAAACCGACCCGCCAGTGCTTCCCTCGGTAATAGTGATGCTATACCGTAACACTTGTTTACCTGTGAAATGTACATTTCCGGTACGCACCGGCGGCGTAAGCACCGCCGGCTTCTGTGTTTATACCCGGAAAGTCAACTAGCGGTGAAGCCGGAATCGCTCCTTTGTTGGTTAGGACTCTATCCGACTCGATCGCAGTCACACGTTGAGTGCGTTGAATAAGATTTAGATTCACATCCTCCTCCCGTAGGTAAGTAATAGACCGTTCAAGCGCATCTAAGATATGTCCATCATCTGCATGTTTACAGAACTAGCTGATTGTTCGATCGTGGGATCCCAATCGGCCAATCGCGATGGCTAACGTGGGTGGTATGTAATCGGGCGTGGCGTCTTCATCGCTAATTCCGGGTAGCGGGCATACCTTGCGCTACCCCCTATTGAGCAATGGTATGGATAGCGTACTGATCGCGATCTATCATCCAGTTCTTCAACATAATTCAGGAATTAGGGTTCTTAGATCATTCAGAGAAAAAGCCTAGGACGAAGGCTACCTCTACGCTTTGAACTTCCGGATTTTCGTAGATAGACACGTGAGTCAGCCCTGGTTGATTAAGTCGTACAGACAAATCCAAGGTAGAAGTTCG"
index = { "A" => 0, "C" => 0, "T" => 0, "G" => 0 }

str.each_char { |char| index[char] += 1 }

print "#{index['A']} #{index['C']} #{index['G']} #{index['T']}"
